#!/usr/bin/env bash
# sitedata.sh - publish honour-roll + live server status as JSON for shadowgain.com.
#
#   ./sitedata.sh            # generate once and publish
#   ./sitedata.sh --install  # also install a cron entry to refresh every 5 minutes
#
# Writes two files into the Caddy web root, served straight off the existing site:
#   https://shadowgain.com/data/honourroll.json
#   https://shadowgain.com/data/status.json
#
# WHY THIS IS A DROPLET SCRIPT AND NOT SERVER CODE
#
# Everything needed already exists outside the game process: character name, level and
# PropertyInt.Age (playtime seconds, maintained by Player_Tick) live in the shard DB, and
# the 021 marker is PropertyBool 9102. Reading them here means no new server code, no
# container mount, no restart to change the feed, and no risk to the running world if the
# exporter breaks. Cowork can iterate on the page without touching the server at all.
#
# The honour roll deliberately lists ONLY hard-path characters. There is no fast-path list
# and no second leaderboard - absence is the signal (021).
set -euo pipefail

KEY="C:/Users/Chris/.ssh/shadowgain_ed25519"
HOST="root@137.184.1.44"
SSH="ssh -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

INSTALL=0
[ "${1:-}" = "--install" ] && INSTALL=1

# The generator runs ON the droplet so cron can call it without this machine being awake.
$SSH "$HOST" 'cat > /opt/ACE/sitedata-gen.sh' <<'REMOTE'
#!/usr/bin/env bash
# Generated by tools/sitedata.sh - refreshes the public JSON feeds.
set -euo pipefail

# 080: leave EVIDENCE when this dies.
#
# This runs from a systemd timer, so a `set -e` death is completely silent: nothing is written,
# nothing complains, and status.json simply stops changing. The panel then freezes on whatever it
# last said - which is worse than reporting an outage, because it is confidently wrong and gives no
# signal at all. That happened: two unguarded greps killed this script and the site read
# "Offline / last updated 4 min ago" for a healthy server until Chris noticed from his phone.
#
# The trap costs nothing and turns an invisible failure into a line with a timestamp and a line
# number. `set -E` is required for it to fire inside functions and subshells.
# EXIT, not ERR. An ERR trap fires for every non-zero command even where the failure is handled,
# so the first version of this wrote FAILED (exit 0) five times in a healthy run - a log full of
# false positives is worse than no log, because it trains you to ignore it. EXIT fires exactly once
# and only when the script genuinely dies.
trap 'rc=$?; if [ "$rc" -ne 0 ]; then
        echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) sitedata-gen FAILED (exit $rc)" >> /opt/ACE/Logs/sitedata-fail.log
      fi' EXIT

cd /opt/ACE
RP=$(grep '^MYSQL_ROOT_PASSWORD=' docker.env | cut -d= -f2)
OUT=/var/www/shadowgain/data
mkdir -p "$OUT"

# MODE: status | roll | both. The two feeds run on different cadences - status every
# 15s (systemd timer) because it should feel live, the roll every 5 min (cron) because
# it is a DB query over every character and barely changes.
#
# 15s, not the 30s this comment claimed until 157. The timer has said 15s since it was
# installed - see the reasoning beside the --install block, which is Chris's and is the
# real decision. A comment that contradicts the unit file a few hundred lines away is how
# someone "corrects" the timer back to a number nobody chose.
MODE="${1:-both}"

q() { docker exec ace-db mysql -uroot -p"$RP" -N -B ace_shard -e "$1" 2>/dev/null; }

# --- honour roll: hard-path characters only ---------------------------------
if [ "$MODE" = "roll" ] || [ "$MODE" = "both" ]; then
# PropertyBool 9102 = ShadowgainForfeitedMarker. A character qualifies when that row is
# absent or false, i.e. it has never taken the fast lane.
#
# 183: the 9102 exclusion STAYS and is now a quiet legacy rule. The fast lane closed in 181, so the
# roll no longer explains itself by it - but the three who took it while it was open stay off, and
# their flags are preserved untouched (Chris: a use may still come).
#
# PropertyInt 390 = Enlightenment, 0-5. Emitted so the page can show the dagger as an ENLIGHTENMENT
# marker instead, Awakened through Cosmic Conscious. WEB ONLY, deliberately: the in-game name marker
# (progression_marker_enabled) stays false because that prefix leaked into VTank fields that are
# machine-compared. Expect 0 for everyone until somebody reaches level 275.
# PropertyInt 25 = Level, 125 = Age (total seconds played).
ROWS=$(q "
SELECT CONCAT(
  '{\"name\":\"', REPLACE(c.name,'\"','\\\\\"'), '\",',
  '\"level\":', COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=25),1), ',',
  '\"skillXp\":', COALESCE((SELECT SUM(p_p) FROM biota_properties_skill WHERE object_Id=c.id),0), ',',
  '\"enlightenment\":', COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=390),0), ',',
  '\"hours\":', ROUND(COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=125),0)/3600,1), '}'
)
FROM \`character\` c
WHERE c.is_Deleted=0 AND c.delete_Time=0
  AND NOT EXISTS (SELECT 1 FROM biota_properties_bool
                  WHERE object_Id=c.id AND type=9102 AND value=1)
  -- 080: level floor + recency, the same shape as the #chat gate (bot: level >= 10 AND active).
  --
  -- WHY A LEVEL FLOOR. Leaving the Academy hands out roughly level 10 for nothing, so a character
  -- created and logged straight back out sat on a list about taking the long road - Admin, level 1,
  -- 0.0 hours. The floor excludes NOTHING anyone earned: the data shows level 11-14 reached inside
  -- half an hour. It removes only characters that never entered the world.
  --
  -- WHY 30 DAYS RATHER THAN THE BOT-S 72 HOURS. They answer different questions. Chat access asks
  -- whether you are participating right now, and 72h suits that. The roll asks whether you walked
  -- the long road - erasing a 33-hour grind from a public leaderboard because someone took a long
  -- weekend reads as a bug, not a rule. Tunable if Chris wants them identical.
  --
  -- Note this uses last_Login_Timestamp ALONE, where the bot deliberately uses two signals. That
  -- column is written once at login and never refreshed, so a player parked in world for weeks
  -- looks idle by it. The bot compensates by watching play counters move, which needs a stored
  -- baseline this stateless query does not have - and at 30 days the difference stops mattering,
  -- which is a second reason not to copy the 72h window.
  --
  -- NO DOUBLE QUOTES IN THIS BLOCK. The whole query sits inside a double-quoted shell string, so a
  -- quotation mark in a SQL comment closes it and bash starts executing the remainder as commands.
  AND COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=25),1) >= ${SG_ROLL_MIN_LEVEL:-10}
  AND c.last_Login_Timestamp >= (UNIX_TIMESTAMP() - ${SG_ROLL_ACTIVITY_DAYS:-30} * 86400)

  -- 183: ANTI-MULE FLOOR. Total skill XP, which is the one number a mule cannot fake.
  --
  -- The level-10 floor above cannot catch this on its own, and the reason is in its own comment:
  -- leaving the Academy hands out roughly level 10 for nothing. So a storage alt that walked out
  -- of the Academy and parked lands on exactly the floor meant to exclude it.
  --
  -- Skill XP separates them cleanly because it can only come from USING skills. Measured on LIVE
  -- 2026-08-20 across every character then passing these filters:
  --
  --     Soul 3,156 / Two Hander 3,691 / Twohander 5,616   - all at 0.0 hours played
  --     High Tides 26,253                                  - 0.2 hours, i.e. actually played
  --
  -- Three mules under 6k, then a 4.7x jump to the first character that had done anything. 10,000
  -- sits in that gap: above what the Academy grants, below anyone who has played at all. It is
  -- deliberately a MULE filter and not a merit bar - a new player clears it within minutes, which
  -- is the intent. The roll says who is walking the road, not who is far along it.
  --
  -- Raise it only with a reason and a fresh look at the distribution. It is a cliff, and anyone
  -- sitting just under it vanishes from a public page with no explanation.
  AND COALESCE((SELECT SUM(p_p) FROM biota_properties_skill WHERE object_Id=c.id),0) >= ${SG_ROLL_MIN_SKILL_XP:-10000}

  -- 069: ONLY accessLevel 0 is eligible. Anything above it - Advocate, Sentinel, Envoy,
  -- Developer, Admin - is excluded from the roll entirely.
  --
  -- This started as a >= 4 filter because the first run listed a level-275 character with
  -- 1.5 hours played, which is precisely what an honour roll for grinding must not
  -- celebrate. Player-only is the stricter version of the same idea, and it buys a second
  -- thing: staff never appear here, so their presence on the server is not publicly
  -- trackable from the site.
  --
  -- Keep this in step with the Ascendant gate in shadowgain_bot.py - the reward and the
  -- roll are meant to answer the same question, and they have drifted apart before.
  AND c.account_Id NOT IN (SELECT accountId FROM ace_auth.account WHERE accessLevel > 0)
-- 159c: the roll reports SKILL XP, not level.
--
-- Chris: instead of level, maybe a tally of the xp skills have earned - shows hard work without
-- being a gauge for competition.
--
-- It is the better metric for a second reason. LEVEL is exactly what the cross-lane hole inflated:
-- fellowship and pass-up XP raise character level and touch skill XP not at all. Trees came out of
-- that test at level 150 with 1.18B of skill XP against 10.25B of character XP. Skill XP can only
-- come from using skills, so it measures the long road directly and cannot be handed to anyone by
-- a fellowship.
--
-- Level is still selected, because the eligibility floor below uses it, and is still sent for
-- anything that wants it - it just stops being what the page shows first.

-- 159b: BY NAME, not by level.
  --
  -- Ordering this list by level made it a leaderboard and people played it as one. A ranked list
  -- answers who is winning; an alphabetical one answers who walked the road, which is what the roll
  -- is actually for. Chris, after a night of drama over it: this should be a fun and stress free
  -- place.
  --
  -- The front-end #-column went with it. Numbering an alphabetical list would be meaningless and
  -- would still read as a rank.
  --
  -- LIMIT raised at the same time: under the old ordering it meant the top 100, a sensible cut.
  -- Alphabetically it would mean everyone up to about the letter M, which is not.
  --
  -- AND NOT A SINGLE DOUBLE QUOTE IN THIS COMMENT. See the warning thirty lines above - I wrote
  -- seven of them here on the first attempt and bash executed the rest of the query as commands.
  ORDER BY c.name ASC
LIMIT 1000;")

{
  printf '{"generated":"%s","characters":[' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '%s' "$(echo "$ROWS" | paste -sd, -)"
  printf ']}\n'
} > "$OUT/.honourroll.json.tmp"
mv -f "$OUT/.honourroll.json.tmp" "$OUT/honourroll.json"
fi

# --- live server status -----------------------------------------------------
if [ "$MODE" = "status" ] || [ "$MODE" = "both" ]; then
UP=false; UPTIME=""
if docker ps --format '{{.Names}}' | grep -q '^ace-server$'; then
  UP=true
  UPTIME=$(docker ps --filter name=ace-server --format '{{.Status}}')
fi

# Players online AND the world's shape, from one serverstatus call.
#
# Landblocks matter more than player count for capacity: ACE ticks its world on a
# SINGLE thread (WorldThreadCount=1), and the cost is driven by how many active
# landblocks and objects are being simulated. Ten players in one dungeon is cheap;
# ten scattered across Dereth is not. So record objects/landblocks, not just heads.
ONLINE=null; LANDBLOCKS=null; OBJECTS=null; CREATURES=null
# 043: did the world actually ANSWER this run? "The container exists" is not the same claim.
# During a graceful drain docker still reports the container Up, so a panel driven off
# `docker ps` alone honestly reads Online for the whole shutdown. A successful serverstatus
# is a liveness probe: if ACE cannot answer its own console it is not serving anyone.
# 039 §E: BOUND THIS READ. It used to find the reply by dumping the whole log twice - once to
# count lines as a marker, once to take everything after it. Correct, and unbounded: the cost
# grew with the container log, which grows forever. At a 49 MB log that was 4.2s per read,
# 8.4s of the timer's 15s period spent finding two lines, and still climbing. See 039 section E.
#
# `--since` asks the daemon for the tail by TIME, so the cost is proportional to the window
# rather than to uptime. A second-granularity timestamp taken before the command may include
# up to a second of unrelated lines, which is why every field below still takes `tail -1` -
# the newest match wins, exactly as it did under the marker scheme.
SERVING=false
if [ "$UP" = true ]; then
  T0=$(date -u +%Y-%m-%dT%H:%M:%S)
  # `sg-roster` rides along on the SAME attach as serverstatus - the attach is the expensive part
  # (a fixed 8s, because `docker attach` never exits on its own), so a second command on it is
  # very nearly free. It names the online characters, which my.shadowgain.com uses to put an
  # "Online" dot beside a player's OWN characters on the logged-in panel.
  #
  # 127c: THIS WAS BRIEFLY BLAMED FOR BREAKING THE PUBLIC HONOUR ROLL, AND IT WAS NOT THE CAUSE.
  # The real fault was the `docker logs` read below being killed by its own 10s timeout, because
  # the container log had grown to 548 MB and `--since` alone still scans the whole file. See
  # the note there. Removing this command did not fix it; adding `--tail` did.
  #
  # `sg-roster` and not `listplayers`: both print the same roster, but listplayers is a
  # Developer-tier command that ShadowgainAudit relays to Discord #audit, and putting it on a
  # 15s timer flooded that channel (125). Both are now in ShadowgainAudit.NotAudited (160), so
  # neither would flood today - but a command meant for polling should be in that set on purpose.
  # Before putting ANY console command on a timer, check it.
  # 157: 8s and 2s were 10 of this script's 13.76s, against a 15s timer - a 1.2s margin, and
  # 129's failure was precisely runs left with no idle gap. Neither number was buying anything.
  #
  # `docker attach` NEVER exits on its own, so this timeout is not a limit, it is the full cost,
  # paid every run. But all it has to do is deliver two lines of stdin; the REPLY is read from the
  # log further down. Measured: the reply is visible **0.13s after the attach closes**, so the
  # timeout was the entire latency. 5/5 delivery at both 1s and 2s with only a 1s wait after.
  #
  # 3s is triple the largest value proven to work, and still returns 5s per run. Run time drops
  # 13.76s -> ~7.8s, so the margin against the 15s timer goes 1.2s -> 7.2s.
  #
  # DO NOT tune this to make the timer faster without re-measuring the whole run. The page polls
  # every 10s, so 10s is the only interval below 15 that a human could notice - and a ~7.8s run
  # against a 10s timer is a 78% duty cycle, which is the thin margin this change exists to remove.
  { echo serverstatus; echo sg-roster; } | timeout -s KILL 3 docker attach --sig-proxy=false ace-server >/dev/null 2>&1 || true
  sleep 1
  # `--tail` IS NOT OPTIONAL, IT IS THE WHOLE COST. 039 section E bounded this read with
  # `--since` so it would not grow with uptime - but `--since` only bounds the OUTPUT. Docker
  # still scans forward through the json log to find the window, so the call stays O(file size).
  # At 548 MB that measured **14.2 seconds**; with `--tail 4000` alongside it, **66 ms** - Docker
  # seeks from the END instead. Same data, 200x faster.
  #
  # This is what broke the public honour roll. One status run had grown to ~32s against a timer
  # firing every 15s, so runs piled up two and three deep and their `docker attach` calls
  # contended for the one console. A collided run parses no serverstatus, SERVING stays false,
  # and status.json says the world is OFFLINE while it is perfectly healthy.
  #
  # 4000 lines is ~40s of a busy log, so the reply we just asked for cannot scroll past before we
  # read it; every parse below still takes `tail -1`, so extra history is harmless.
  # 157: `docker logs --tail` STOPPED WORKING, and took the public honour roll offline with it.
  #
  # 154 capped this log with logrotate + copytruncate. Docker survives the truncation for WRITING
  # - it appends from offset 0 again, no sparse file, verified - but `--tail` seeks backwards from
  # a stale offset and returns NOTHING. Silently, exit 0. Every field below came back empty and
  # status.json said OFFLINE with 14 people playing: 129's exact symptom from the opposite cause.
  #
  # Reading the json file directly keeps what 129 bought - cost is O(tail), not O(file size) -
  # and does not depend on Docker's seek state at all. jq unescapes the `log` field, which is the
  # job `docker logs` was doing for us (`\u003e` for `>` and friends), so the greps are unchanged.
  #
  # THE TIME FILTER IS NOT OPTIONAL. `tail -n` alone would happily parse a STALE serverstatus
  # reply from before a shutdown and report the world as live. Comparing the first 19 characters
  # matches T0's format; comparing the whole RFC3339 string would NOT, because '.' sorts before
  # 'Z', so every sub-second stamp would test as older than a whole-second T0.
  #
  # `fromjson?` rather than plain `fromjson`: a partially-written last line is normal on a file
  # being appended to, and one unparseable line must not empty the whole read.
  LOGF=$(docker inspect --format '{{.LogPath}}' ace-server 2>/dev/null || true)
  if [ -n "$LOGF" ] && [ -r "$LOGF" ]; then
    SS=$(tail -n 4000 "$LOGF" 2>/dev/null \
         | jq -R -r --arg t0 "$T0" 'fromjson? | select(.time[0:19] >= $t0) | .log' 2>/dev/null || true)
  else
    # Fallback for any host where the log file is not readable from here. Same call 129 landed on.
    SS=$(timeout -s KILL 10 docker logs --since "$T0" --tail 4000 ace-server 2>&1 || true)
  fi

  # `[0-9,]` and `tr -d ','`, NOT `[0-9]`: ACE thousand-separates these, so once the shard passed
  # a thousand objects `Total Server Objects: 2,779` matched as **2** and `Creatures: 1,534` as
  # **1**. Pre-existing and independent of the read above - it was simply invisible while the
  # numbers were small, and would have been reported as fact the moment the read started working.
  N=$(printf '%s' "$SS" | grep -oE '[0-9,]+ players online' | tail -1 | grep -oE '^[0-9,]+' | tr -d ',' || true)
  if [ -n "$N" ]; then ONLINE=$N; SERVING=true; fi

  L=$(printf '%s' "$SS" | grep -oE 'Landblocks: [0-9,]+ active' | tail -1 | grep -oE '[0-9,]+' | tr -d ',' || true)
  [ -n "$L" ] && LANDBLOCKS=$L

  O=$(printf '%s' "$SS" | grep -oE 'Total Server Objects: [0-9,]+' | tail -1 | grep -oE '[0-9,]+$' | tr -d ',' || true)
  [ -n "$O" ] && OBJECTS=$O

  C=$(printf '%s' "$SS" | grep -oE 'Creatures: [0-9,]+' | tail -1 | grep -oE '[0-9,]+$' | tr -d ',' || true)
  [ -n "$C" ] && CREATURES=$C

  # The online character NAMES, for the logged-in panel's own-characters dot.
  #
  # THE MARKER MUST COME OFF. Names arrive as "† Black Breath" - the hard-lane prefix is cosmetic
  # and is NOT part of character.name, so leaving it on would make every hard-lane character fail
  # the comparison and read as permanently offline.
  #
  # The leading space before the colon is load-bearing: it matches a roster row and NOT
  # sg-roster's trailing "Total connected Players: 10", which has no space there. Deduped because
  # a `--tail` window can hold two runs' output.
  #
  # The account id is DISCARDED. It is not needed to answer "is this character online", and an
  # account id is a different class of fact from a character name.
  # `l.strip()` and not `l.rstrip(<newline>)`: an escaped newline inside this single-quoted
  # python one-liner is one layer of quoting away from becoming a REAL newline, which breaks
  # the literal, errors python, and is then swallowed by `|| true` - leaving an empty roster
  # and every character reading offline, silently. It did exactly that. No backslashes here.
  NAMES_JSON=$(printf '%s' "$SS" \
    | grep -aE ' : [0-9]+[[:space:]]*$' \
    | grep -avE 'Total connected Players' \
    | sed -E 's/^.*INFO : //' \
    | sed -E 's/ : [0-9]+[[:space:]]*$//' \
    | sed -E 's/^[^A-Za-z0-9]+//' \
    | grep -av '^[[:space:]]*$' \
    | awk '!seen[$0]++' \
    | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin]))' 2>/dev/null || true)

fi

# NOT IN status.json, AND NOT IN THE WEB ROOT.
#
# status.json is public and the honour roll reads it. Chris, 2026-08-15: *"what's not allowed is
# a view to other characters online state"* - other people's accounts. So the roster lands in
# /opt/ACE, which Caddy does not serve, and only the character portal's API reads it, to light a
# dot beside characters on the VIEWER'S OWN account behind login. The public character page
# carries no presence at all.
#
# An empty or unparseable list becomes [] rather than null: "not in the list" already means
# offline, and null would need special-casing at the other end for no gain.
[ -z "${NAMES_JSON:-}" ] && NAMES_JSON="[]"

# Temp file and mv, so a reader can never catch a half-written array.
printf '{"generated":"%s","names":%s}
' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$NAMES_JSON"   > /opt/ACE/.online-names.json.tmp
chmod 644 /opt/ACE/.online-names.json.tmp
mv /opt/ACE/.online-names.json.tmp /opt/ACE/online-names.json

# --- host load ---------------------------------------------------------------
# 2 vCPU / 4GB since the 025 upgrade. ACE's MAIN loop is single-threaded, but physics
# and landblock-group ticking do parallelise (both enabled here), so the second core is
# doing real work. ACE's own guidance: 2 threads/4GB serves 1-10 players, 4 threads/8GB
# serves 11-49 - these numbers are what decide when to move up.
# 043: ONE `docker stats` call, with a timeout, instead of three without.
#
# `docker stats --no-stream` blocks while the daemon is stopping a container - which is
# exactly when this script most needs to finish and report Offline. Three untimed calls
# meant a stopping server could stall the run past its own 15s timer, leaving status.json
# stale at the last "Online" - the panel then lied for as long as the daemon was busy.
# Collapsing to one call also cuts ~2/3 of the runtime on every normal run.
STATS=$(timeout -s KILL 10 docker stats --no-stream --format '{{.Name}}|{{.CPUPerc}}|{{.MemUsage}}' 2>/dev/null || true)
CPU_ACE=$(printf '%s\n' "$STATS" | awk -F'|' '/^ace-server\|/{gsub(/%/,"",$2); print $2}' | head -1)
CPU_DB=$(printf '%s\n' "$STATS"  | awk -F'|' '/^ace-db\|/{gsub(/%/,"",$2); print $2}'     | head -1)
MEM_ACE=$(printf '%s\n' "$STATS" | awk -F'|' '/^ace-server\|/{split($3,a," "); print a[1]}' | head -1 | sed 's/MiB$//')
LOAD1=$(awk '{print $1}' /proc/loadavg)
MEM_USED=$(free -m | awk '/Mem:/{print $3}')
MEM_AVAIL=$(free -m | awk '/Mem:/{print $7}')
MEM_TOTAL=$(free -m | awk '/Mem:/{print $2}')
SWAP_USED=$(free -m | awk '/Swap:/{print $3}')

# Emit `null` for anything that is not a bare number. These land UNQUOTED in status.json, so
# one unexpected value corrupts the entire feed and the page shows "unreachable" - a much
# worse failure than a missing metric. Docker switches MemUsage to GiB above 1024MiB, which
# would have written `1.2GiB` straight into a JSON number field; ACE has simply never been
# big enough to hit it.
for v in CPU_ACE CPU_DB MEM_ACE LOAD1 MEM_USED MEM_AVAIL MEM_TOTAL SWAP_USED; do
  eval "val=\$$v"
  case "$val" in
    ''|*[!0-9.]*) eval "$v=null" ;;
  esac
done

# 043: worldOpened now means "the world is serving RIGHT NOW", not "the world opened at
# some point this container's life".
#
# It used to be a grep -c over the whole log, so once the marker appeared it stayed >0 until
# the container restarted and the log reset. During a graceful drain that kept reading
# truthy, which is why honourroll.html's `d.worldOpened` gate could not catch a draining
# server no matter what the page did - the exporter was answering a different question.
#
# The log check is KEPT and ANDed rather than replaced: it is the cheap proof the world ever
# came up, and SERVING is the proof it is still answering. Deliberately NOT using
# `docker logs --tail` here - on a long-uptime server the marker scrolls out of any bounded
# window and the panel would report Offline for a perfectly healthy world.
#
# 074: SERVING is not sufficient either. A shutdown that closes the world but never exits
# the process keeps answering `serverstatus`, because the console is part of that process.
# Chris hit exactly this: sessions dropped at 11:52:53, every login was refused for the
# next seven minutes - including one from an address that was not his - and the panel read
# healthy throughout, because all three signals were individually TRUE. The container was
# up. The world HAD opened. The console did reply.
#
# So the fourth question is "did it shut down AFTER it last opened?". Ordering, not
# presence: compare the last "World is now open" against the last shutdown notice. Line
# numbers are a valid comparator because the log is append-only, and taking both from ONE
# capture keeps them on the same scale - which also collapses what used to be two full
# `docker logs` reads into one.
#
# 039 §E: THE REASONING ABOVE WAS RIGHT AND THE CONCLUSION WAS WRONG. Refusing `--tail` because
# the marker scrolls out of a bounded window is correct. Re-reading the ENTIRE log every 15s
# to avoid that is not the only alternative - remembering what was already seen is.
#
# Measured: a 49 MB log took 4.2s per full read (0.6s user, 1.6s sys, 244,714 lines) and the
# log grows ~65 MB/day, so the cost climbed with uptime and with nothing else. That is the
# load average that rose 0.18 -> 1.44 across a 26h run while player count sat at zero.
#
# So: scan only what is NEW since the last pass, and carry the answers forward in a state
# file keyed on the container's StartedAt. A restart invalidates the key and reseeds with one
# full read - which is exactly when the log resets anyway, so the seed is cheap.
#
# Ordering now compares log TIMESTAMPS rather than line numbers. Line numbers were valid only
# because both came from one whole-log capture; across incremental reads they restart at 1 and
# would compare garbage. `--timestamps` emits RFC3339Nano UTC, which sorts lexically.
LOG=""
WORLD_EVER=0
DRAINING=false
if [ "$UP" = true ]; then
  SCAN_STATE="${SG_SCAN_STATE:-/opt/ACE/.logscan}"
  C_STARTED=$(docker inspect -f '{{.State.StartedAt}}' ace-server 2>/dev/null || true)

  ST_STARTED=""; ST_SCAN=""; ST_EVER=0; ST_OPEN=""; ST_DOWN=""
  # shellcheck disable=SC1090
  [ -f "$SCAN_STATE" ] && { . "$SCAN_STATE" 2>/dev/null || true; }

  # Stamped BEFORE the read, so anything logged while the read is in flight is picked up next
  # pass rather than falling down the gap between them. A re-read is harmless: every update
  # below is idempotent.
  NOW_SCAN=$(date -u +%Y-%m-%dT%H:%M:%S)

  if [ -n "$C_STARTED" ] && [ "$ST_STARTED" = "$C_STARTED" ] && [ -n "$ST_SCAN" ]; then
    LOG=$(timeout -s KILL 10 docker logs --timestamps --since "$ST_SCAN" ace-server 2>&1 || true)
  else
    ST_EVER=0; ST_OPEN=""; ST_DOWN=""
    LOG=$(timeout -s KILL 30 docker logs --timestamps ace-server 2>&1 || true)
  fi

  NEW_OPEN=$(printf '%s\n' "$LOG" | grep "World is now open" | tail -1 | awk '{print $1}' || true)
  [ -n "$NEW_OPEN" ] && { ST_OPEN=$NEW_OPEN; ST_EVER=1; }
  WORLD_EVER=$ST_EVER

  # `|| true` on BOTH, and it is not decoration. This script runs under `set -euo pipefail`,
  # and grep exits 1 when it matches nothing - which is the NORMAL case here, because a freshly
  # restarted container has no shutdown line in its log at all. Without the guard the command
  # substitution fails, set -e kills the generator, and status.json simply stops being written:
  # the panel then freezes on whatever it last said and drifts further from reality every minute.
  #
  # Which is exactly what happened - the page read "Offline / last updated 4 min ago" while the
  # server was up and healthy. The line above already carried `|| true` for this same reason and
  # the guard was not carried over to the two new greps.
  NEW_DOWN=$(printf '%s\n' "$LOG" | grep -E "Server is shutting down|shutting down NOW" | tail -1 | awk '{print $1}' || true)
  [ -n "$NEW_DOWN" ] && ST_DOWN=$NEW_DOWN

  # String comparison, not numeric: these are RFC3339Nano stamps now, not line numbers.
  # `>` inside [[ ]] is a lexical compare, which is what sorts these correctly. Using [ ]
  # here would need it escaped and would silently do the wrong thing if it were not.
  if [ -n "$ST_DOWN" ] && { [ -z "$ST_OPEN" ] || [[ "$ST_DOWN" > "$ST_OPEN" ]]; }; then
    DRAINING=true
  fi

  # Written last, and only after the scan succeeded, so a failed pass re-scans the same window
  # next time instead of advancing past events it never read. Temp-then-rename so a crash
  # mid-write cannot leave a truncated state file that would silently reseed every run.
  printf 'ST_STARTED=%s\nST_SCAN=%s\nST_EVER=%s\nST_OPEN=%s\nST_DOWN=%s\n' \
    "'$C_STARTED'" "'$NOW_SCAN'" "'$ST_EVER'" "'$ST_OPEN'" "'$ST_DOWN'" \
    > "$SCAN_STATE.tmp" && mv -f "$SCAN_STATE.tmp" "$SCAN_STATE"
fi
WORLD=false
if [ "$UP" = true ] && [ "${WORLD_EVER:-0}" -gt 0 ] && [ "$SERVING" = true ] && [ "$DRAINING" = false ]; then
  WORLD=true
fi

# --- uptime, for the restart-cadence question --------------------------------
# Seconds since the ace-server container started, straight from Docker rather than
# inferred. Without this, reading a memory trend out of history.jsonl means GUESSING
# where the restarts were from drops in memAceMB - which works only while a restart
# is the sharpest thing in the series, and silently mis-segments as soon as it is not.
#
# The open question this exists to answer: does ACE's memory plateau or creep? A leak
# needs a scheduled restart; a plateau does not. Either way the answer needs uptime on
# the same row as the memory reading, or the two cannot be correlated.
#
# ANSWERED ENOUGH TO ACT ON (2026-08-10, 26.1h run, 5,440 samples). Near-idle memory
# drifts +1.28 MB/h - about 57 days of headroom - and the idle floor is flat within ~20 MB
# across sixteen hours. No scheduled restart is warranted. Not fully closed: a naive fit
# over the same run gives +4.26 MB/h, still under the 5 MB/h leak threshold but not zero.
#
# WHY THE TWO NUMBERS DIFFER, and the trap for whoever reads this series next: memAceMB
# tracks LANDBLOCKS, so a run that ends busier than it began reads as a rising leak. This
# run did exactly that - new players arrived in its final hours and lifted landblocks
# 2.0 -> 13.9. Always control for occupancy (filter landblocks <= 3, or regress on
# landblocks and time together) before calling a slope a leak. See Task.md 039 section E.
ACE_UPTIME=null
if [ "$UP" = true ]; then
  STARTED=$(docker inspect -f '{{.State.StartedAt}}' ace-server 2>/dev/null || true)
  if [ -n "$STARTED" ]; then
    S=$(date -u -d "$STARTED" +%s 2>/dev/null || true)
    [ -n "$S" ] && ACE_UPTIME=$(( $(date -u +%s) - S ))
  fi
fi

# The in-game marker prefix is a live dial (023). Expose it so the site can follow it
# rather than hardcoding the dagger - otherwise switching the in-game prefix to the
# ASCII fallback would leave the website and the game disagreeing.
#
# --default-character-set=utf8mb4 is REQUIRED, not decorative. The column IS utf8mb4 and
# the dagger IS stored correctly as E2 80 A0, but the mysql client defaults to latin1 on
# output and silently transcodes it to the single CP1252 byte 0x86. That is not valid
# UTF-8, so the whole status.json becomes unparseable to any browser. This is the only
# non-ASCII value the exporter touches, which is why it never mattered until now.
#
# Caught only by decoding explicitly as UTF-8 - checking it in a terminal is useless,
# because a CP1252 console decodes 0x86 back to a dagger and the file looks fine.
PREFIX=$(docker exec ace-db mysql -uroot -p"$RP" -N -B --default-character-set=utf8mb4 ace_shard -e "SELECT value FROM config_properties_string WHERE \`key\`='progression_marker_prefix';" 2>/dev/null | head -1)
[ -z "$PREFIX" ] && PREFIX="† "

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$OUT/.status.json.tmp" <<JSON
{
  "generated": "$NOW",
  "online": $WORLD,
  "draining": $DRAINING,
  "containerUp": $UP,
  "playersOnline": $ONLINE,
  "uptime": "$UPTIME",
  "worldOpened": $WORLD,
  "markerPrefix": "$(printf '%s' "$PREFIX" | sed 's/"/\\"/g')",
  "world": {
    "landblocksActive": $LANDBLOCKS,
    "objects": $OBJECTS,
    "creatures": $CREATURES
  },
  "host": {
    "cpuAcePct": $CPU_ACE,
    "cpuDbPct": $CPU_DB,
    "memAceMB": $MEM_ACE,
    "memUsedMB": $MEM_USED,
    "memAvailMB": $MEM_AVAIL,
    "memTotalMB": $MEM_TOTAL,
    "swapUsedMB": $SWAP_USED,
    "load1": $LOAD1
  }
}
JSON
mv -f "$OUT/.status.json.tmp" "$OUT/status.json"

# Written temp-then-rename on purpose. `>` truncates the file BEFORE filling it, so a
# browser fetching during that window gets an empty or partial file and the page shows
# "feed is currently unreachable" - which is exactly what Chris hit. The page refreshes
# every 60s against a file rewritten every 5 minutes, so a collision was only a matter
# of time. mv on the same filesystem is atomic: a reader sees the whole old file or the
# whole new one, never a half-written one.

# --- rolling history ----------------------------------------------------------
# A snapshot cannot answer "can we take ten players" - that needs a time series, so
# every run appends one line. At 5-minute cron that is 288 lines/day; capped at
# ~30 days so it can never grow unbounded on a 48GB disk.
#
# This is the file to look at when deciding on a resize: correlate playersOnline
# and landblocksActive against cpuAcePct and memAvailMB at the busiest moments.
#
# aceUptimeS makes the memory question answerable: a run is every row whose uptime is
# monotonically increasing, and the slope of memAceMB within one run is the only number
# that means anything. Comparing across a restart boundary compares two different
# processes.
printf '{"t":"%s","players":%s,"landblocks":%s,"objects":%s,"cpuAce":%s,"cpuDb":%s,"memAceMB":%s,"memAvailMB":%s,"swapMB":%s,"load1":%s,"aceUptimeS":%s}\n' \
  "$NOW" "$ONLINE" "$LANDBLOCKS" "$OBJECTS" "$CPU_ACE" "$CPU_DB" "$MEM_ACE" "$MEM_AVAIL" "$SWAP_USED" "$LOAD1" "$ACE_UPTIME" >> "$OUT/history.jsonl"

if [ "$(wc -l < "$OUT/history.jsonl")" -gt 9000 ]; then
  tail -9000 "$OUT/history.jsonl" > "$OUT/history.tmp" && mv "$OUT/history.tmp" "$OUT/history.jsonl"
fi

fi   # end status block

chown -R caddy:caddy "$OUT" 2>/dev/null || true
chmod 644 "$OUT"/*.json "$OUT"/*.jsonl 2>/dev/null || true
REMOTE

$SSH "$HOST" 'chmod +x /opt/ACE/sitedata-gen.sh && /opt/ACE/sitedata-gen.sh && echo generated'

if [ "$INSTALL" = "1" ]; then
  # Two cadences on purpose. The status feed is what should feel live, and it is cheap -
  # one console call plus some /proc reads. The honour roll is a DB query over every
  # character and changes maybe once an hour, so refreshing it that often would be waste.
  #
  # 15s, not 30s. Chris: "30s is actually a long time if you actively start refreshing a
  # webpage looking for an update.. people will do that shit too." Correct - the metric
  # that matters is the impatient human hitting F5, not the average staleness.
  #
  # cron cannot go below one minute, so status uses a systemd timer instead.
  echo "==> installing systemd timer (status, 15s) + cron (roll, 5 min)"
  $SSH "$HOST" 'bash -s' <<"INSTALL_EOF"
cat > /etc/systemd/system/shadowgain-status.service <<UNIT
[Unit]
Description=Shadowgain live status feed
After=docker.service
[Service]
Type=oneshot
ExecStart=/opt/ACE/sitedata-gen.sh status
UNIT

cat > /etc/systemd/system/shadowgain-status.timer <<UNIT
[Unit]
Description=Refresh Shadowgain status feed every 15s
[Timer]
OnBootSec=45s
OnUnitActiveSec=15s
AccuracySec=1s
[Install]
WantedBy=timers.target
UNIT

systemctl daemon-reload
systemctl enable --now shadowgain-status.timer >/dev/null 2>&1
# roll stays on cron, and no longer needs to do the status work
(crontab -l 2>/dev/null | grep -v sitedata-gen; echo "*/5 * * * * /opt/ACE/sitedata-gen.sh roll >/dev/null 2>&1") | crontab -
echo "  timer: $(systemctl is-active shadowgain-status.timer)"
crontab -l | tail -1 | sed "s/^/  cron: /"
INSTALL_EOF
fi

# Freshness assert, not just HTTP 200. A 200 proves the web server is serving A file; it says
# nothing about whether THIS run produced it. Without this, a generator that died before writing
# still reported "live" against the previous run's output.
NOW=$(date -u +%s)
for f in status.json honourroll.json; do
  AGE=$(( NOW - $($SSH "$HOST" "stat -c %Y /var/www/shadowgain/data/$f 2>/dev/null || echo 0") ))
  if [ "$AGE" -gt 600 ]; then
    echo "!! $f is ${AGE}s old - the generator did not write it this run"
    exit 1
  fi
done

echo "==> live:"
for f in honourroll status; do
  printf "  https://shadowgain.com/data/%s.json  %s\n" "$f" \
    "$(curl -s -o /dev/null -w 'HTTP %{http_code}' "https://shadowgain.com/data/$f.json")"
done
