#!/usr/bin/env bash
# sitedata.sh - publish honour-roll + live server status as JSON for shadowgain.com.
#
#   ./sitedata.sh            # generate once and publish
#   ./sitedata.sh --install  # also install a cron entry to refresh every 5 minutes
#
# Writes two files into the Caddy web root, served straight off the existing site:
#   https://shadowgain.com/data/honourroll.json
#   https://shadowgain.com/data/status.json
#
# WHY THIS IS A DROPLET SCRIPT AND NOT SERVER CODE
#
# Everything needed already exists outside the game process: character name, level and
# PropertyInt.Age (playtime seconds, maintained by Player_Tick) live in the shard DB, and
# the 021 marker is PropertyBool 9102. Reading them here means no new server code, no
# container mount, no restart to change the feed, and no risk to the running world if the
# exporter breaks. Cowork can iterate on the page without touching the server at all.
#
# The honour roll deliberately lists ONLY hard-path characters. There is no fast-path list
# and no second leaderboard - absence is the signal (021).
set -euo pipefail

KEY="C:/Users/Chris/.ssh/shadowgain_ed25519"
HOST="root@137.184.1.44"
SSH="ssh -i $KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

INSTALL=0
[ "${1:-}" = "--install" ] && INSTALL=1

# The generator runs ON the droplet so cron can call it without this machine being awake.
$SSH "$HOST" 'cat > /opt/ACE/sitedata-gen.sh' <<'REMOTE'
#!/usr/bin/env bash
# Generated by tools/sitedata.sh - refreshes the public JSON feeds.
set -euo pipefail
cd /opt/ACE
RP=$(grep '^MYSQL_ROOT_PASSWORD=' docker.env | cut -d= -f2)
OUT=/var/www/shadowgain/data
mkdir -p "$OUT"

# MODE: status | roll | both. The two feeds run on different cadences - status every
# 30s (systemd timer) because it should feel live, the roll every 5 min (cron) because
# it is a DB query over every character and barely changes.
MODE="${1:-both}"

q() { docker exec ace-db mysql -uroot -p"$RP" -N -B ace_shard -e "$1" 2>/dev/null; }

# --- honour roll: hard-path characters only ---------------------------------
if [ "$MODE" = "roll" ] || [ "$MODE" = "both" ]; then
# PropertyBool 9102 = ShadowgainForfeitedMarker. A character qualifies when that row is
# absent or false, i.e. it has never taken the fast lane.
# PropertyInt 25 = Level, 125 = Age (total seconds played).
ROWS=$(q "
SELECT CONCAT(
  '{\"name\":\"', REPLACE(c.name,'\"','\\\\\"'), '\",',
  '\"level\":', COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=25),1), ',',
  '\"hours\":', ROUND(COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=125),0)/3600,1), '}'
)
FROM \`character\` c
WHERE c.is_Deleted=0 AND c.delete_Time=0
  AND NOT EXISTS (SELECT 1 FROM biota_properties_bool
                  WHERE object_Id=c.id AND type=9102 AND value=1)
  -- Exclude characters on Developer/Admin accounts. The first run listed a level-275
  -- character with 1.5 hours played, which is precisely what an honour roll for grinding
  -- must not celebrate. Those are hand-boosted test characters; real players sit at
  -- Advocate or below.
  AND c.account_Id NOT IN (SELECT accountId FROM ace_auth.account WHERE accessLevel >= 4)
ORDER BY COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=25),1) DESC,
         COALESCE((SELECT value FROM biota_properties_int WHERE object_Id=c.id AND type=125),0) DESC
LIMIT 100;")

{
  printf '{"generated":"%s","characters":[' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '%s' "$(echo "$ROWS" | paste -sd, -)"
  printf ']}\n'
} > "$OUT/.honourroll.json.tmp"
mv -f "$OUT/.honourroll.json.tmp" "$OUT/honourroll.json"
fi

# --- live server status -----------------------------------------------------
if [ "$MODE" = "status" ] || [ "$MODE" = "both" ]; then
UP=false; UPTIME=""
if docker ps --format '{{.Names}}' | grep -q '^ace-server$'; then
  UP=true
  UPTIME=$(docker ps --filter name=ace-server --format '{{.Status}}')
fi

# Players online AND the world's shape, from one serverstatus call.
#
# Landblocks matter more than player count for capacity: ACE ticks its world on a
# SINGLE thread (WorldThreadCount=1), and the cost is driven by how many active
# landblocks and objects are being simulated. Ten players in one dungeon is cheap;
# ten scattered across Dereth is not. So record objects/landblocks, not just heads.
ONLINE=null; LANDBLOCKS=null; OBJECTS=null; CREATURES=null
if [ "$UP" = true ]; then
  MARK=$(docker logs ace-server 2>&1 | wc -l)
  echo "serverstatus" | timeout -s KILL 8 docker attach --sig-proxy=false ace-server >/dev/null 2>&1 || true
  sleep 2
  SS=$(docker logs ace-server 2>&1 | tail -n +$((MARK+1)))

  N=$(printf '%s' "$SS" | grep -oE '[0-9]+ players online' | tail -1 | grep -oE '^[0-9]+' || true)
  [ -n "$N" ] && ONLINE=$N

  L=$(printf '%s' "$SS" | grep -oE 'Landblocks: [0-9]+ active' | tail -1 | grep -oE '[0-9]+' || true)
  [ -n "$L" ] && LANDBLOCKS=$L

  O=$(printf '%s' "$SS" | grep -oE 'Total Server Objects: [0-9]+' | tail -1 | grep -oE '[0-9]+$' || true)
  [ -n "$O" ] && OBJECTS=$O

  C=$(printf '%s' "$SS" | grep -oE 'Creatures: [0-9]+' | tail -1 | grep -oE '[0-9]+$' || true)
  [ -n "$C" ] && CREATURES=$C
fi

# --- host load ---------------------------------------------------------------
# 2 vCPU / 4GB since the 025 upgrade. ACE's MAIN loop is single-threaded, but physics
# and landblock-group ticking do parallelise (both enabled here), so the second core is
# doing real work. ACE's own guidance: 2 threads/4GB serves 1-10 players, 4 threads/8GB
# serves 11-49 - these numbers are what decide when to move up.
CPU_ACE=$(docker stats --no-stream --format '{{.Name}} {{.CPUPerc}}' 2>/dev/null | awk '/ace-server/{gsub(/%/,"",$2); print $2}')
CPU_DB=$(docker stats --no-stream --format '{{.Name}} {{.CPUPerc}}' 2>/dev/null | awk '/ace-db/{gsub(/%/,"",$2); print $2}')
MEM_ACE=$(docker stats --no-stream --format '{{.Name}} {{.MemUsage}}' 2>/dev/null | awk '/ace-server/{print $2}' | sed 's/MiB//')
LOAD1=$(awk '{print $1}' /proc/loadavg)
MEM_USED=$(free -m | awk '/Mem:/{print $3}')
MEM_AVAIL=$(free -m | awk '/Mem:/{print $7}')
MEM_TOTAL=$(free -m | awk '/Mem:/{print $2}')
SWAP_USED=$(free -m | awk '/Swap:/{print $3}')
[ -z "$CPU_ACE" ] && CPU_ACE=null
[ -z "$CPU_DB" ] && CPU_DB=null
[ -z "$MEM_ACE" ] && MEM_ACE=null

WORLD=$(docker logs ace-server 2>&1 | grep -c "World is now open" || true)

# --- uptime, for the restart-cadence question --------------------------------
# Seconds since the ace-server container started, straight from Docker rather than
# inferred. Without this, reading a memory trend out of history.jsonl means GUESSING
# where the restarts were from drops in memAceMB - which works only while a restart
# is the sharpest thing in the series, and silently mis-segments as soon as it is not.
#
# The open question this exists to answer: does ACE's memory plateau or creep? A leak
# needs a scheduled restart; a plateau does not. Either way the answer needs uptime on
# the same row as the memory reading, or the two cannot be correlated.
ACE_UPTIME=null
if [ "$UP" = true ]; then
  STARTED=$(docker inspect -f '{{.State.StartedAt}}' ace-server 2>/dev/null || true)
  if [ -n "$STARTED" ]; then
    S=$(date -u -d "$STARTED" +%s 2>/dev/null || true)
    [ -n "$S" ] && ACE_UPTIME=$(( $(date -u +%s) - S ))
  fi
fi

# The in-game marker prefix is a live dial (023). Expose it so the site can follow it
# rather than hardcoding the dagger - otherwise switching the in-game prefix to the
# ASCII fallback would leave the website and the game disagreeing.
#
# --default-character-set=utf8mb4 is REQUIRED, not decorative. The column IS utf8mb4 and
# the dagger IS stored correctly as E2 80 A0, but the mysql client defaults to latin1 on
# output and silently transcodes it to the single CP1252 byte 0x86. That is not valid
# UTF-8, so the whole status.json becomes unparseable to any browser. This is the only
# non-ASCII value the exporter touches, which is why it never mattered until now.
#
# Caught only by decoding explicitly as UTF-8 - checking it in a terminal is useless,
# because a CP1252 console decodes 0x86 back to a dagger and the file looks fine.
PREFIX=$(docker exec ace-db mysql -uroot -p"$RP" -N -B --default-character-set=utf8mb4 ace_shard -e "SELECT value FROM config_properties_string WHERE \`key\`='progression_marker_prefix';" 2>/dev/null | head -1)
[ -z "$PREFIX" ] && PREFIX="† "

NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$OUT/.status.json.tmp" <<JSON
{
  "generated": "$NOW",
  "online": $UP,
  "playersOnline": $ONLINE,
  "uptime": "$UPTIME",
  "worldOpened": $WORLD,
  "markerPrefix": "$(printf '%s' "$PREFIX" | sed 's/"/\\"/g')",
  "world": {
    "landblocksActive": $LANDBLOCKS,
    "objects": $OBJECTS,
    "creatures": $CREATURES
  },
  "host": {
    "cpuAcePct": $CPU_ACE,
    "cpuDbPct": $CPU_DB,
    "memAceMB": $MEM_ACE,
    "memUsedMB": $MEM_USED,
    "memAvailMB": $MEM_AVAIL,
    "memTotalMB": $MEM_TOTAL,
    "swapUsedMB": $SWAP_USED,
    "load1": $LOAD1
  }
}
JSON
mv -f "$OUT/.status.json.tmp" "$OUT/status.json"

# Written temp-then-rename on purpose. `>` truncates the file BEFORE filling it, so a
# browser fetching during that window gets an empty or partial file and the page shows
# "feed is currently unreachable" - which is exactly what Chris hit. The page refreshes
# every 60s against a file rewritten every 5 minutes, so a collision was only a matter
# of time. mv on the same filesystem is atomic: a reader sees the whole old file or the
# whole new one, never a half-written one.

# --- rolling history ----------------------------------------------------------
# A snapshot cannot answer "can we take ten players" - that needs a time series, so
# every run appends one line. At 5-minute cron that is 288 lines/day; capped at
# ~30 days so it can never grow unbounded on a 48GB disk.
#
# This is the file to look at when deciding on a resize: correlate playersOnline
# and landblocksActive against cpuAcePct and memAvailMB at the busiest moments.
#
# aceUptimeS makes the memory question answerable: a run is every row whose uptime is
# monotonically increasing, and the slope of memAceMB within one run is the only number
# that means anything. Comparing across a restart boundary compares two different
# processes.
printf '{"t":"%s","players":%s,"landblocks":%s,"objects":%s,"cpuAce":%s,"cpuDb":%s,"memAceMB":%s,"memAvailMB":%s,"swapMB":%s,"load1":%s,"aceUptimeS":%s}\n' \
  "$NOW" "$ONLINE" "$LANDBLOCKS" "$OBJECTS" "$CPU_ACE" "$CPU_DB" "$MEM_ACE" "$MEM_AVAIL" "$SWAP_USED" "$LOAD1" "$ACE_UPTIME" >> "$OUT/history.jsonl"

if [ "$(wc -l < "$OUT/history.jsonl")" -gt 9000 ]; then
  tail -9000 "$OUT/history.jsonl" > "$OUT/history.tmp" && mv "$OUT/history.tmp" "$OUT/history.jsonl"
fi

fi   # end status block

chown -R caddy:caddy "$OUT" 2>/dev/null || true
chmod 644 "$OUT"/*.json "$OUT"/*.jsonl 2>/dev/null || true
REMOTE

$SSH "$HOST" 'chmod +x /opt/ACE/sitedata-gen.sh && /opt/ACE/sitedata-gen.sh && echo generated'

if [ "$INSTALL" = "1" ]; then
  # Two cadences on purpose. The status feed is what should feel live, and it is cheap -
  # one console call plus some /proc reads. The honour roll is a DB query over every
  # character and changes maybe once an hour, so refreshing it that often would be waste.
  #
  # 15s, not 30s. Chris: "30s is actually a long time if you actively start refreshing a
  # webpage looking for an update.. people will do that shit too." Correct - the metric
  # that matters is the impatient human hitting F5, not the average staleness.
  #
  # cron cannot go below one minute, so status uses a systemd timer instead.
  echo "==> installing systemd timer (status, 15s) + cron (roll, 5 min)"
  $SSH "$HOST" 'bash -s' <<"INSTALL_EOF"
cat > /etc/systemd/system/shadowgain-status.service <<UNIT
[Unit]
Description=Shadowgain live status feed
After=docker.service
[Service]
Type=oneshot
ExecStart=/opt/ACE/sitedata-gen.sh status
UNIT

cat > /etc/systemd/system/shadowgain-status.timer <<UNIT
[Unit]
Description=Refresh Shadowgain status feed every 15s
[Timer]
OnBootSec=45s
OnUnitActiveSec=15s
AccuracySec=1s
[Install]
WantedBy=timers.target
UNIT

systemctl daemon-reload
systemctl enable --now shadowgain-status.timer >/dev/null 2>&1
# roll stays on cron, and no longer needs to do the status work
(crontab -l 2>/dev/null | grep -v sitedata-gen; echo "*/5 * * * * /opt/ACE/sitedata-gen.sh roll >/dev/null 2>&1") | crontab -
echo "  timer: $(systemctl is-active shadowgain-status.timer)"
crontab -l | tail -1 | sed "s/^/  cron: /"
INSTALL_EOF
fi

echo "==> live:"
for f in honourroll status; do
  printf "  https://shadowgain.com/data/%s.json  %s\n" "$f" \
    "$(curl -s -o /dev/null -w 'HTTP %{http_code}' "https://shadowgain.com/data/$f.json")"
done
